### ISSUE TITLE
What's the data being sent?

### ISSUE THREAD

**Issue by notflip** [jonathanedgecombe/absmouse#3]
This may be a strange place for my question, but I can't find any information on this.
Down below, **what data is actually being sent?** I'm trying to test my hid mouse in Python, but I can't find any testing data or tutorials to move the mouse.

```
void AbsMouse_::report(void)
{
	uint8_t buffer[5];
	buffer[0] = _buttons;
	buffer[1] = _x & 0xFF;
	buffer[2] = (_x >> 8) & 0xFF;
	buffer[3] = _y & 0xFF;
	buffer[4] = (_y >> 8) & 0xFF;
	HID().SendReport(1, buffer, 5);
}
```

**Comment by xcarcelle** [comment]
@notflip the whole array buffer[5] is sent over the HID datalink with a comprehension on the host size of the data received to parse them correctly with the HID Descriptor sent early on at handshake. Have you been able to test this project with different devices ?
